#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sonatiina.Resource", IsApplication=true)]

namespace Sonatiina
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050003
			public const int pref_language_values = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int pref_languages = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int pref_theme_values = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int pref_themes = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060009
			public const int lista_kuvaus_kirkas = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int lista_kuvaus_punainen = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int lista_kuvaus_tumma = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int lista_otsikko_vihrea = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int my_purple = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int osoite_tausta_tumma = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int primary_color_text = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int primary_color_text_dark = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int sonaatti_bar_tumma = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int sonaatti_pinkki = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int sonaatti_tausta = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int sonaatti_tausta_tumma = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int sonaatti_taustapinkki = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int sonaatti_violetti = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int theme_devicedefault_light_background = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int valkoinen = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int more = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000f
			public const int aukioloajat = 2131361807;
			
			// aapt resource value: 0x7f0a0008
			public const int button1 = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int button2 = 2131361801;
			
			// aapt resource value: 0x7f0a000c
			public const int container = 2131361804;
			
			// aapt resource value: 0x7f0a0007
			public const int creator = 2131361799;
			
			// aapt resource value: 0x7f0a000b
			public const int feedItemsListView = 2131361803;
			
			// aapt resource value: 0x7f0a000d
			public const int frameLayout1 = 2131361805;
			
			// aapt resource value: 0x7f0a0000
			public const int imageView1 = 2131361792;
			
			// aapt resource value: 0x7f0a0004
			public const int linearLayout1 = 2131361796;
			
			// aapt resource value: 0x7f0a0011
			public const int menu_about = 2131361809;
			
			// aapt resource value: 0x7f0a0010
			public const int menu_preferences = 2131361808;
			
			// aapt resource value: 0x7f0a000e
			public const int osoite = 2131361806;
			
			// aapt resource value: 0x7f0a0001
			public const int textView1 = 2131361793;
			
			// aapt resource value: 0x7f0a0003
			public const int textView2 = 2131361795;
			
			// aapt resource value: 0x7f0a0002
			public const int textView3 = 2131361794;
			
			// aapt resource value: 0x7f0a0005
			public const int textView4 = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int title = 2131361798;
			
			// aapt resource value: 0x7f0a000a
			public const int toolbar = 2131361802;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FeedItemListItemLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int lang = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Settings = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int toolbar = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Wilhelmiina = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int top_menus = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07000b
			public const int a = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int aboutButton = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int b = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int openhours = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int pref_appearance_title = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int pref_language_title = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int pref_select_language = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int pref_select_theme = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int pref_theme = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int settingsButton = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int version = 2131165187;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int DarkTheme = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int DialogStyle = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int DialogStylePink = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int MyCustomTheme = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int PinkTheme = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int Theme_Custom = 2131230725;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
